# Generated by Django 4.1 on 2022-10-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsito', '0003_comment_comment_blogsito_co_created_e3b9f5_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['publish'], name='blogsito_po_publish_17cdfb_idx'),
        ),
    ]
